version: "3"

services:                                                                               
  db:
    build:
      context: ./dpa-postgres
      dockerfile: Dockerfile
    container_name: dpa_postgres
    env_file: .env 
    ports:
       - "5435:5435"

  api:
    build:
      context: ./dpa-flask
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"

  python:
    build:
      context: ./dpa-python
      dockerfile: Dockerfile
    container_name: dpa_python
    env_file: .env
    ports:
      - "8090:8090"


  shiny:
    build:
      context: ./dpa-shiny
      dockerfile: Dockerfile
    container_name: shiny
    environment:
      - VIRTUAL_HOST=shiny.DOMAIN.tld
    ports:
      - "2234:2234"